pyrachnid/__init__.py
from flask import Flask, request

from pyrachnid.assets import assets
from pyrachnid.config import app_config
from pyrachnid.main import main as main_blueprint


def create_app(app_env):
    app = Flask(__name__)
    app.config.from_object(app_config[app_env])

    app.register_blueprint(main_blueprint, url_prefix='')

    assets.init_app(app)

    @app.before_request
    def clear_cache():
        if 'localhost' in request.host_url:
            app.jinja_env.cache = {}

    return app

pyrachnid/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

import views

pyrachnid/main/views.py
from flask import (
    jsonify,
    make_response,
    render_template,
    request
)

from . import main


@main.route('/healthcheck')
def healthcheck():
    return make_response(jsonify({
        'status_code': 200,
        'text': 'OK'
    }))


@main.route('/')
def home():
    context = {'action': None}
    return render_template('index.html')


@main.route('/add')
def add_new_site():
    context = {
        'action': 'set domain'
    }
    return render_template('add_new_site.html', context=context)


@main.route('/')
def view_existing_site():
    return render_template('view_existing_site.html')

pyrachnid/templates/add_new_site.html
{% extends 'main_layout.html' %}

{% block breadcrumb %}
  {% include 'components/breadcrumb.html' %}
{% endblock %} 

{% block page_prompt %}
  <h5>What is the domain of the website you want to scrape?</h5>
{% endblock %}

{% block page_form %}
  <form action="">
    <div class="twelve columns">
      <input class="u-full-width input" type="url" placeholder="Ex. https://store.com" id="setDomain">
      <input class="button mtm one-third-width" type="submit" value="Next">
    </div>
  </form>
{% endblock %}

pyrachnid/templates/components/breadcrumb.html
<h5 class="grey">
{% if context and context.action %}
  <a class="undecorated" href="{{ url_for('main.home')}}">
    rrscraper
  </a> > add new site > {{ context.action }}
{% else %}
  Welcome to rrscraper
{% endif %}
</h5>

pyrachnid/templates/index.html
{% extends 'main_layout.html' %}

{% block breadcrumb %}
  {% include 'components/breadcrumb.html' %}
{% endblock %}

{% block page_prompt %}
  <h5>What would you like to do?</h5>
{% endblock %}

{% block page_form %}
  <div class="six columns">
    <a class="button jumboButton" href="{{ url_for('main.add_new_site') }}">Add new site</a>
  </div>
  <div class="six columns">
    <a class="button jumboButton" href="{{ url_for('main.view_existing_site') }}">View existing site</a>
  </div>
{% endblock %}

pyrachnid/templates/main_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>

  {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
</head>

<body>
  <div class="">
    {% block content %}
    <div class="container">
      <div class="row">
        <div class="half column">
          <section class="mtm">

            {% block breadcrumb %}{% endblock %}

            <div class="tac center mtxxl">
              <form>
                {% block page_prompt %}{% endblock %}
                <div class="row mtm">
                  {% block page_form %}{% endblock %}
                </div>
              </form>
            </div>

          </section>
        </div>
      </div>
    </div>

    {% endblock %}
  </div>
</body>

</html>